--
-- 0061__schedule_pagamento_confirmado_log.sql
--
-- Contexto: o topico Kafka olimpio.pagamento.confirmado (publicado pelo fiserv-service
-- para cartao e pelo asaas-service para PIX) passou a ser consumido pelo
-- schedule-service (PagamentoConfirmadoConsumer/PagamentoConfirmadoService), que aplica
-- a baixa na fin_parcela (data_pagamento, valor_pago, forma_pagamento + vinculo
-- id_parcela_cartao/id_parcela_pix).
--
-- Esta migracao cria a tabela de auditoria/idempotencia do consumo: cada evento
-- processado gera uma linha aqui; a combinacao (id_gateway, status) evita
-- processar o mesmo evento duas vezes. Nenhuma tabela/coluna existente e alterada.
--

CREATE TABLE IF NOT EXISTS public.fin_pagamento_confirmado_log (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_parcela          bigint,
    id_transacao        bigint,
    id_pessoa           bigint,
    forma_pagamento     character varying(30),
    status              character varying(30),
    valor               numeric(15,2),
    id_gateway          character varying(100),
    data_confirmacao    timestamp without time zone,
    processado_em       timestamp without time zone DEFAULT now(),
    resultado           character varying(40)
);

ALTER TABLE public.fin_pagamento_confirmado_log OWNER TO postgres;

COMMENT ON TABLE public.fin_pagamento_confirmado_log IS
  'Auditoria/idempotencia do consumo do topico olimpio.pagamento.confirmado pelo schedule-service (baixa na fin_parcela)';
COMMENT ON COLUMN public.fin_pagamento_confirmado_log.id_gateway IS
  'Identificador no gateway (ipgTransactionId no Fiserv / providerChargeId no PSP PIX)';
COMMENT ON COLUMN public.fin_pagamento_confirmado_log.resultado IS
  'BAIXADA | ESTORNADA | STATUS_IGNORADO | PARCELA_NAO_ENCONTRADA';

DO $DO$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fin_pagamento_confirmado_log_id_parcela_fkey') THEN
        ALTER TABLE ONLY public.fin_pagamento_confirmado_log
            ADD CONSTRAINT fin_pagamento_confirmado_log_id_parcela_fkey FOREIGN KEY (id_parcela) REFERENCES public.fin_parcela(id);
    END IF;
END
$DO$;

CREATE UNIQUE INDEX IF NOT EXISTS ux_fin_pagto_log_gateway_status
    ON public.fin_pagamento_confirmado_log (id_gateway, status) WHERE id_gateway IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_fin_pagto_log_id_parcela
    ON public.fin_pagamento_confirmado_log (id_parcela);
