quarkus.http.port=${QUARKUS_HTTP_PORT:8098}
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.limits.max-header-size=32K

quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=${DATABASE_URL:postgresql://localhost:5454/olimpio}
quarkus.datasource.username=${DATABASE_USER:postgres}
quarkus.datasource.password=${DATABASE_PASSWORD:postgres}
quarkus.cache.caffeine."biblioteca-obra-cache".expire-after-write=1h
quarkus.cache.caffeine."biblioteca-exemplar-cache".expire-after-write=1h