quarkus.http.port=${QUARKUS_HTTP_PORT:8098}
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.limits.max-header-size=32K

quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=${DATABASE_URL:postgresql://localhost:5454/olimpio}
quarkus.datasource.username=${DATABASE_USER:postgres}
quarkus.datasource.password=${DATABASE_PASSWORD:postgres}
quarkus.datasource."biblioteca".db-kind=postgresql
quarkus.datasource."biblioteca".jdbc.url=${BIBLIOTECA_JDBC_URL:jdbc:postgresql://localhost:5454/olimpio}
quarkus.datasource."biblioteca".reactive.url=${DATABASE_URL:postgresql://localhost:5454/olimpio}
quarkus.datasource."biblioteca".username=${DATABASE_USER:postgres}
quarkus.datasource."biblioteca".password=${DATABASE_PASSWORD:postgres}
quarkus.flyway."biblioteca".locations=db/migration/biblioteca
quarkus.flyway."biblioteca".migrate-at-start=true
quarkus.flyway."biblioteca".baseline-on-migrate=true
quarkus.flyway."biblioteca".baseline-version=1
quarkus.flyway."biblioteca".validate-on-migrate=false

quarkus.cache.caffeine."biblioteca-obra-cache".expire-after-write=1h
quarkus.cache.caffeine."biblioteca-exemplar-cache".expire-after-write=1h