export const API_PATHS = {
  auth: {
    login: '/api/login',
    logout: '/api/login/logout',
  },
  basico: {
    agenda: '/api/basico/agenda',
    usuario: '/api/basico/usuario',
    pessoaFisica: '/api/basico/pessoa-fisica',
    pessoaJuridica: '/api/basico/pessoa-juridica',
    pessoa: '/api/basico/pessoa',
    funcionario: '/api/basico/funcionario',
    feriado: '/api/basico/feriado',
    logradouro: '/api/basico/logradouro',
    unidade: '/api/basico/unidade',
    rede: '/api/basico/rede',
    sala: '/api/educacao/sala',
    diaAula: '/api/educacao/dia-aula',
    turnoEducacao: '/api/educacao/turno-educacao',
    tempoAula: '/api/educacao/tempo-aula',
    tipoSala: '/api/educacao/tipo-sala',
    curriculo: '/api/educacao/curriculo',
    componenteCurricular: '/api/educacao/componente-curricular',
    grupoComponenteCurricular: '/api/educacao/grupo-componente-curricular',
    tipoMatrizCurricular: '/api/educacao/tipo-matriz-curricular',
    modalidade: '/api/educacao/modalidade',
    matrizCurricular: '/api/educacao/matriz-curricular',
    curriculoUnidade: '/api/educacao/curriculo-unidade',
    curriculoAtividadeComplementar: '/api/educacao/curriculo-atividade-complementar',
    materialEscolarCurso: '/api/educacao/material-escolar-curso',
    requisitoMatriz: '/api/educacao/requisito-matriz',
    criterio: '/api/educacao/criterio',
    oferecimentoComponenteCurricular: '/api/educacao/oferecimento-componente-curricular',
    oferecimentoCurso: '/api/educacao/oferecimento-curso',
    ocorrenciaComponenteCurricular: '/api/educacao/ocorrencia-componente-curricular',
    professor: '/api/professor/professor',
    aulaAnexo: '/api/professor/aula-anexo',
    alunoContrato: '/api/educacao/aluno-contrato',
    atividadeComplementar: '/api/educacao/atividade-complementar',
    desistente: '/api/educacao/desistente',
    matricula: '/api/educacao/matricula',
    rematricula: '/api/educacao/rematricula',
  },
  central: {
    ligacao: '/api/central/ligacao',
    tipoPausa: '/api/central/tipo-pausa',
    pausa: '/api/central/pausa',
    pacotes: '/api/central/pacotes',
    prospecto: '/api/central/prospecto',
    operacional: '/api/central/operacional',
    operacionalUsuario: '/api/central/operacional-usuario',
    coordenador: '/api/central/coordenador',
    turnoTrabalho: '/api/central/turno-trabalho',
    turnoUsuario: '/api/central/turno-usuario',
    resultadoContato: '/api/central/resultado-contato',
  },
  comercial: {
    consultor: '/api/comercial/consultor',
    prospectoList: '/api/comercial/prospecto-list',
  },
  financeiro: {
    configuracaoCaixa: '/api/financeiro/configuracao-caixa',
    custoServico: '/api/financeiro/custo-servico',
    regraCancelamento: '/api/financeiro/regra-cancelamento',
    cancelamento: '/api/financeiro/cancelamento',
    caixa: '/api/financeiro/caixa',
    movimentacaoFinanceira: '/api/financeiro/movimentacao-financeira',
    modeloEmail: '/api/cobranca/modelo-email',
    enviarEmailLote: '/api/cobranca/enviar-email-lote',
    alunoContrato: '/api/educacao/aluno-contrato',
    conta: {
      gestaoConta: '/api/conta/gestaoConta',
      controlePagamento: '/api/conta/controlePagamento',
    },
  },
  educacao: {
    nap: '/api/educacao/nap',
    gerirNap: '/api/view/nap/listGerirNap',
  },
  cobranca: {
    gerirCobranca: '/api/view/cobranca/listGerirCobranca',
  },
  relatorios: {
    tabela: '/api/relatorios/tabela',
    grafico: '/api/relatorios/grafico',
    mapa: '/api/relatorios/mapa',
    dashboard: '/api/relatorios/dashboard',
    estrutura: '/api/relatorios/estrutura',
    dimensao: '/api/relatorios/dimensao',
    medida: '/api/relatorios/medida',
    filtro: '/api/relatorios/filtro',
    mapaRegra: '/api/relatorios/mapa-regra',
    painelPainel: '/api/relatorios/painel-painel',
    georeferencia: '/api/relatorios/georeferencia',
    estruturaColuna: '/api/relatorios/estrutura-coluna',
    relatorioDisponiveis: '/api/relatorios/relatorio/disponiveis',
    organograma: '/api/relatorios/organograma',
    indicadorGauge: '/api/relatorios/indicador-gauge',
    indicadorGaugeDisponiveis: '/api/relatorios/indicador-gauge/disponiveis',
    indicadorGaugeExecutar: '/api/relatorios/indicador-gauge/executar',
  },
  curriculo: {
    vaga: '/api/curriculo/vaga',
    criarEntrevistas: '/api/curriculo/vaga/criar-entrevistas',
    enviarVagasAlunos: '/api/curriculo/vaga/enviar-vagas-alunos',
  },
  notificacoes: {
    regras: '/api/notificacoes/regras',
    notificacao: '/api/notificacoes/notificacao',
  },
  asaas: {
    pixEnviarEmail: '/api/asaas/pix/enviar-email',
  },
  view: {
    usuario: '/api/view/usuario/listUsuario',
    unidade: '/api/view/unidade/listUnidade',
    impressora: '/api/view/impressora/listImpressora',
    diaSemana: '/api/view/diaSemana/listDiaSemana',
    tipoPausa: '/api/view/tipoPausa/listTipoPausa',
    turnoTrabalho: '/api/view/turnoTrabalho/listTurnoTrabalho',
    conta: {
      gestaoConta: '/api/view/conta/gestaoConta',
      controlePagamento: '/api/view/conta/controlePagamento',
    },
    digitalizacaoDocumento: {
      digitalizacaoDocumento: '/api/view/digitalizacaoDocumento/digitalizacaoDocumento',
      turmasDisponiveis: '/api/view/digitalizacaoDocumento/turmasDisponiveis',
      carregarDiasAula: '/api/view/digitalizacaoDocumento/carregarDiasAula',
      digitalizacaoChamadas: '/api/view/digitalizacaoDocumento/digitalizacaoChamadas',
      carregarOcorrencia: '/api/view/digitalizacaoDocumento/carregarOcorrencia',
      autoCompleteAluno: '/api/view/digitalizacaoDocumento/autoCompleteAluno',
      carregarDocumentosAluno: '/api/view/digitalizacaoDocumento/carregarDocumentosAluno',
      salvarDocumentoAluno: '/api/view/digitalizacaoDocumento/salvarDocumentoAluno',
      inserirArquivo: '/api/view/digitalizacaoDocumento/inserirArquivo',
      inserirChamada: '/api/view/digitalizacaoDocumento/inserirChamada',
      salvarChamada: '/api/view/digitalizacaoDocumento/salvarChamada',
    },
  },
} as const;

export type ApiPath = typeof API_PATHS[keyof typeof API_PATHS][keyof typeof API_PATHS[keyof typeof API_PATHS]];